### PR TITLE
Convert site to a static site generator and update theme

### PR DESCRIPTION
**Pull request by jplsek**
- Update theme to be more similar to a landing page.
- Add a navigation bar
- Move content to the about page
- Put some images locally instead of a link (they weren't rendering in
some browsers)
- (I also updated the grammar is some places - very minor though)

Static site generation benefits:
- Auto generate `<head>`:
	- Favicon types for different devices
	- Theme color
	- Meta tags/SEO
- Auto minification
- JS routing for supported browsers
For developing:
- Templating
- Uses reactjs for simple DOM manipulation
- Hot reload

See readme for more info. If you do not like the static site generator chosen, we can choose something else.

We talked a bit about the stats page, but I may just let you handle that, as I'm not really sure how to go about updating that cleanly. We can talk more on Discord about this if you'd like.

(Some of the formatting in the code may be odd for large paragraphs, but that's because the code is ran through a formatter.)

Screen Shot 2019-12-25 at 21 47 25

### CODE REVIEW

**Comment by ajayyy** [comment]
Very nice. Is there a way to make it not break when JS is disabled?

**Comment by OfficialNoob** [comment]
Would this be cached on a CDN because i don't think the website currently is?
[Netlify](https://www.netlify.com/) looks interesting for hosting "static" websites.

**Comment by jplsek** [comment]
Rebased with master and formatting changes.

**Comment by ajayyy** [comment]
TODO: cleanup view on mobile

**Pull request merged**
